### ISSUE TITLE
r 9 380

### ISSUE THREAD

**Issue by gennadiv** [Genoil/ZECMiner#10]
у меня то-же не работает Видеокарта R9 380 3 карты -всё по нулям
c:\nheqminer_v0.1b_R2\genoil-zec-miner-0.3.2>genoil-te-6.exe -c zec.suprno
2142 -u gennadiv.1 -p x -P 0 -g 0 1 2 -i 13
# Genoil's ZEC miner - trial & error release!

based on (early) Tromp solver

made possible by John, ocminer (suprnova), feeleep (coinmine.pl) and 110GH

thanks for your donation!
BTC: 1Nu2fMCEBjmnLzqb8qUJpKgq5RoEWFhNcW
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d
ZEC: ???

Using OpenCL platform: AMD Accelerated Parallel Processing
gpu#0: Tonga
gpu#1: Tonga
gpu#2: Tonga
zec#0 loading binary kernels/cache/zec-Tonga-128.bin
zec#0 loading binary kernels/cache/zec-Tonga-128.bin
zec#0 initialized.zec#0 initialized.zec#1 loading binary kernels/cache/zec
-128.bin
zec#1 loading binary kernels/cache/zec-Tonga-128.bin
zec#1 initialized.zec#1 initialized.zec#2 loading binary kernels/cache/zec
-128.bin
zec#2 loading binary kernels/cache/zec-Tonga-128.bin
zconn Connecting to zec.suprnova.cc:2142
zec#0: 0.0S/s   zec#1: 0.0S/s   zec#2: 0.0S/s   total: 0.0S/s
zec#2 initialized.zec#2 initialized.zconn Connected!
zconn subscribed
zconn authorized worker gennadiv.1
zconn subscribed
zconn received new job #2d1
zec#0: 0.0S/s   zec#1: 0.0S/s   zec#2: 0.0S/s   total: 0.0S/s
zec#0: 0.0S/s   zec#1: 0.0S/s   zec#2: 0.0S/s   total: 0.0S/s

**Comment by Genoil** [comment]
english?
