### ISSUE TITLE
APPCRASH on Windows 7

### ISSUE THREAD

**Issue by ikonduktor** [Genoil/ZECMiner#16]
when i start miner there is error:

Сигнатура проблемы:
  Имя события проблемы:   APPCRASH
  Имя приложения:  genoil.exe
  Версия приложения:    0.0.0.0
  Отметка времени приложения:   581327a2
  Имя модуля с ошибкой:    genoil.exe
  Версия модуля с ошибкой:  0.0.0.0
  Отметка времени модуля с ошибкой: 581327a2
  Код исключения:  c000001d
  Смещение исключения:    000000000001240b
  Версия ОС:    6.1.7601.2.1.0.256.1
  Код языка:    1049
  Дополнительные сведения 1:  1f20
  Дополнительные сведения 2:  1f20f2abc2f09878c62890bf4cbf202d
  Дополнительные сведения 3:  9f49
  Дополнительные сведения 4:  9f495ccb255f4e50f16412cd53be1f62

What it could be?

**Comment by molitar** [comment]
Finally got it working after repeatedly trying to start it. Also I had to start it the first several times from elevated command prompt and not the batch file even though I elevated it.
