### ISSUE TITLE
non avx / avx2

### ISSUE THREAD

**Issue by mo35** [Genoil/ZECMiner#20]
quite few people having insta crashes , we managed to narrow it down to SSE2 only procs , i3 , i5 , i7 works fine

**Comment by r120a** [comment]
I can confirm that I am running a Celeron 1840 and it instantly crashes.  I did however download the Intel SDE which emulates all extensions and it ran within that environment until my machine locked up :-)

Link to SDE

https://software.intel.com/en-us/articles/intel-software-development-emulator

**Comment by Genoil** [comment]
Thank you very much! The Tromp blake2 host lib required this to be enabled. With SilentArmy not needed, so glad I patched that in first.
