### ISSUE TITLE
instant crash with 0.4

### ISSUE THREAD

**Issue by nerdralph** [Genoil/ZECMiner#21]
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: genoil.exe
  Application Version:  0.0.0.0
  Application Timestamp:    5815137e
  Fault Module Name:    genoil.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   5815137e
  Exception Code:   c000001d
  Exception Offset: 000000000000ff5b
  OS Version:   6.1.7601.2.1.0.256.4
  Locale ID:    4105
  Additional Information 1: 1f20
  Additional Information 2: 1f20f2abc2f09878c62890bf4cbf202d
  Additional Information 3: a1a8
  Additional Information 4: a1a8675fedd95ed1c3aa44feba74ddf9

Platform Win7/64, 16.10.1 driver, Rx 470
eXtremal's miner version 0.2.2 silentarmy kernel works fine on the same machine (but only with 1 instance in config.txt).  ~27 sol/s.

**Comment by mo35** [comment]
https://github.com/Genoil/ZECMiner/issues/20 
most probably already reported , related to cpu extensions

**Comment by nerdralph** [comment]
@mo35 This is on a Core i5, which has AVX.

**Comment by Genoil** [comment]
How's 0.4.1 working for you?

**Comment by nerdralph** [comment]
Working fine now.  Seems a touch slower than eXtremal's silentarmy build.  I'm getting 25-26 sol/s with yours.  Maybe local/global work differences?  eXtremal's defaults to 256/8192, and I was unable to improve on that when I tried varying it up/down.

Tried -i, but it doesn't work:
error: unrecognised option '-i'

**Comment by nerdralph** [comment]
closing as fixed in 0.4.1
