### ISSUE TITLE
never starts. just crash

### ISSUE THREAD

**Issue by jjziets** [Genoil/ZECMiner#23]
Windows 10.64Bit with AMD 16.9.1

AMD 390x,390x380, HD7990(2GPU's) HD7990(1GPU) and HD8990. 

Miner just crash alwasy.

**Comment by Genoil** [comment]
Try any version >= 0.4.1

**Comment by the-Arioch** [comment]
@jjziets there are a number of test runs - start1.bat, start2.bat and so one - try them one by one and say which starts crashing

**Comment by jjziets** [comment]
No. 4.1 still just pop up genoil stop running. Not sure what is wrong.
