### ISSUE TITLE
Always using integrated graphics

### ISSUE THREAD

**Issue by sammy007** [Genoil/ZECMiner#25]
I have integrated graphics and also R9 290. Miner always trying to use intel GPU. No way to switch.

**Comment by arnpham** [comment]
Try uninstalling or disabling Intel graphics

**Comment by mohnori** [comment]
Its can't detect AMD cards, so no mining.

**Comment by Amythal** [comment]
you need to add the following parameter
-P 1 
(with uppercase, plat, P: set OpenCL platform id)

**Comment by Genoil** [comment]
Add -P 1 to start.bat

**Comment by mohnori** [comment]
Thanks we are mining now looool

**Comment by sammy007** [comment]
Thanks totally missed out this option.
