### ISSUE TITLE
Genoil 0.41 

### ISSUE THREAD

**Issue by nukepower** [Genoil/ZECMiner#28]
zconn Connected!
zconn subscribed
zconn received new job #cb298e064403d62ff13c
zec-sa#0: 0.0S/s        total: 0.0S/s
zconn received new job #44267f8d7bfad5830a69
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zconn received new job #c442452480d4a9c5bc88
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s

any setting im not doing so it hashes ?.
genoil.exe -c us1-zcash.flypool.org:3333 -u ZEC address.rig2 -p z

only works on RX 400 series i guess it's hashing a way on  my three 470 there doing at least 25 sols each or better at stock setting and firmware ,

**Comment by Genoil** [comment]
So this is Pitcairn or Tahiti not working?

**Comment by terrence81** [comment]
I have the same problem on R9 280X and its Tahiti :(

**Comment by ghost** [comment]
Same on HD7950 Tahiti

**Comment by mohnori** [comment]
Its happen after running the miner more than 30 minutes , I use -i parameter but its not work , any way to fix it ? or use -i parameter ?.

**Comment by nukepower** [comment]
2 Pitcairn r7 370 not working 
1 Tahiti r9 280  not working 
3  Ellesmere RX 470 working 

my three rx470 work great at stock around 25 to 28 sols
 I put one on a molded bios it does 30 to 35 sols .  

Question is there a flag to turn on XnSub or will it even be needed with the silent army kernels ?. 
also noticed a big decease in hash if i turn on any CPU cores for more hash with on the fly CPU software  , no complaints my 470's hit 90 something with no CPU cores on getting two more GPU i hope on black Friday, nice deals then and all are back to modded bios .
and till i can use my  lower GPU with this miner, i put everything back on nice hash, i want to keep them all in one place using max hash with GPU and CPU if the software allows, but on the fly is my ZEC home just like ethermine.org is for ETH .I plan to donate as soon as cash allows it.
