### ISSUE TITLE
This miner will work with Intel HD 510? Win 10 x64.

### ISSUE THREAD

**Issue by tor888** [Genoil/ZECMiner#34]
## At least I have now 0Sol/s,and this ::

C:\Users\p\Desktop\ZECMiner-master\releases\genoil-zec-miner-0.4.1>genoil.exe -c zec.suprnova.cc:2142 -u wes.wes -p x -P 0
# Genoil's ZEC miner 0.4 - ft. Silent Army

using Silent Army kernels by mrb

Made possible by tromp, ocminer (suprnova), feeleep (coinmine.pl) and 110GH

Thanks for your donation! (BTC)
Silent Army: 1DbGfE695VUs3kcsy6cX6sLjTmsPawmwvj
Genoil : 1Nu2fMCEBjmnLzqb8qUJpKgq5RoEWFhNcW

Using OpenCL platform: Intel(R) OpenCL
gpu#0: Intel(R) HD Graphics 510
zec-sa#0: 0.0S/szec-sa#0 loading binary kernels/cache/zec-sa-Intel(R) HD Graphics 510-64.bin
zconn Connecting to zec.suprnova.cc:2142
total: 0.0S/s
zec-sa#0clCreateBuffer(-61)
zec-sa#0 Mining thread quitzconn Connected!
zconn subscribed
zconn authorized worker wes.wes
zconn subscribed
zconn received new job #4f
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zconn received new job #50
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s`

DEV you've can comment plz.

**Comment by the-Arioch** [comment]
come one, pal, you can do better than putting blurry pictures onto a temporary soon-to-be-deleted external sites.

at very least you could put the picture right here, but even better just log here the very text!

https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/windows_dos_copy.mspx#top

http://www.howtogeek.com/howto/windows-vista/copy-to-the-clipboard-from-the-windows-command-prompt/

**Comment by tor888** [comment]
## the-Arioch Thanx!

C:\Users\p\Desktop\ZECMiner-master\releases\genoil-zec-miner-0.4.1>genoil.exe -c zec.suprnova.cc:2142 -u wes.wes -p x -P 0

# Genoil's ZEC miner 0.4 - ft. Silent Army

using Silent Army kernels by mrb

Made possible by tromp, ocminer (suprnova), feeleep (coinmine.pl) and 110GH

Thanks for your donation! (BTC)
Silent Army: 1DbGfE695VUs3kcsy6cX6sLjTmsPawmwvj
Genoil : 1Nu2fMCEBjmnLzqb8qUJpKgq5RoEWFhNcW

Using OpenCL platform: Intel(R) OpenCL
gpu#0: Intel(R) HD Graphics 510
zec-sa#0: 0.0S/szec-sa#0 loading binary kernels/cache/zec-sa-Intel(R) HD Graphics 510-64.bin
zconn Connecting to zec.suprnova.cc:2142
total: 0.0S/s
zec-sa#0clCreateBuffer(-61)
zec-sa#0 Mining thread quitzconn Connected!
zconn subscribed
zconn authorized worker wes.wes
zconn subscribed
zconn received new job #4f
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zconn received new job #50
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s
zec-sa#0: 0.0S/s        total: 0.0S/s

**Comment by tor888** [comment]
It will work with Intel HD 510-530 or not???

**Comment by the-Arioch** [comment]
for now it does not even work with AMD OpenCL GPU....

https://github.com/Genoil/ZECMiner/issues/18

but it is good you registered the ticket, sooner or later it would probably has the attention

**Comment by the-Arioch** [comment]
I wonder if Intel integrated video can be made to allocate 2GB system RAM for ocl buffers...

https://github.com/Genoil/ZECMiner/issues/44

Maybe BIOS...

**Comment by Genoil** [comment]
AMD only for now. Next release will incldue opton to lower memory usage. Migth help
