### ISSUE TITLE
How do I connect this miner to my own zcash node?

### ISSUE THREAD

**Issue by benjaminpratt** [Genoil/ZECMiner#35]
Does anyone know how to connect this to my own zcash node, or is this just for stratum? Thanks

**Comment by nukepower** [comment]
depend what AMD card you have it only works with RX 400 series AMD cards but that seems to be being fixed as i type..

to connect any  stratum-server, and it looks like stratum only for now .
use  this 
genoil.exe -c  stratum-server here  -u  ZEC t or z address or  pools user -p passwd usually anything if needed

**Comment by Genoil** [comment]
stratum only, sorry.
