### ISSUE TITLE
Doesn't detect my R290 when my GTX1070 is installed

### ISSUE THREAD

**Issue by Josh-Rusch** [Genoil/ZECMiner#39]
I swapped slots so the AMD is in the first slot and have my display hooked up to the AMD and still no joy. After I swapped cards the nvidia driver was temporarily not associated with the card and that's the only time it detected my AMD card and started correctly. No matter what I try for -g, it seems to go with the nvidia card, even when it's the secondary card and not even hooked up to a monitor

Using OpenCL platform: NVIDIA CUDA
gpu#0: GeForce GTX 1070
zec-sa#0: 0.0S/s        zconn Connecting to us1-zcash.flypool.org:3333total: 0.0S/s

zec-sa#0 loading binary kernels/cache/zec-sa-GeForce GTX 1070-64.bin
zconn Connected!
zconn subscribed
zconn received new job #57d649828038a22484cb
zec-sa#0clEnqueueReadBuffer(-5)
zec-sa#0 Mining thread quitzec-sa#0: 0.0S/s     zconn received new job #0c617d5234aa937e46eetotal: 0.0S/s

**Comment by Genoil** [comment]
have you tried -P 1 -P 0 or maybe even -P 2?

**Comment by Josh-Rusch** [comment]
-P 1 seemed to do the trick. I didn't understand what that flag did.

Thanks for the help!
