### ISSUE TITLE
Does not work on GTX1070 and GTX960

### ISSUE THREAD

**Issue by Kayfolom** [Genoil/ZECMiner#43]
`E:\Mining\genoil-zec-miner-0.4.1>genoil.exe -c zec.suprnova.cc:2142 -u Genoil.SilentArmy -p z
Genoil's ZEC miner 0.4 - ft. Silent Army
========================================
using Silent Army kernels by mrb

Made possible by tromp, ocminer (suprnova), feeleep (coinmine.pl) and 110GH

Thanks for your donation! (BTC)
Silent Army: 1DbGfE695VUs3kcsy6cX6sLjTmsPawmwvj
Genoil : 1Nu2fMCEBjmnLzqb8qUJpKgq5RoEWFhNcW

Using OpenCL platform: NVIDIA CUDA
gpu#0: GeForce GTX 1070
gpu#1: GeForce GTX 960
zec-sa#0 loading binary kernels/cache/zec-sa-GeForce GTX 1070-64.bin
zec-sa#0: 0.0S/s        zec-sa#1: 0.0S/s        total: 0.0S/s
zconn Connecting to zec.suprnova.cc:2142
zec-sa#1 compiling kernels/zec-sa.cl...
zconn Connected!
zconn subscribed
zconn authorized worker Genoil.SilentArmy
zconn subscribed
zconn received new job #346
zec-sa#0clEnqueueReadBuffer(-5)
zec-sa#0 Mining thread quit
E:\Mining\genoil-zec-miner-0.4.1>pause`

`E:\Mining\genoil-zec-miner-0.4.2>genoil.exe -c zec.suprnova.cc:2142 -u Genoil.SilentArmy -p z
Genoil's ZEC miner 0.4.2 - ft. Silent Army
========================================
using Silent Army kernels by mrb

Made possible by tromp, ocminer (suprnova), feeleep (coinmine.pl) and 110GH

Thanks for your donation! (BTC)
Silent Army: 1DbGfE695VUs3kcsy6cX6sLjTmsPawmwvj
Genoil : 1Nu2fMCEBjmnLzqb8qUJpKgq5RoEWFhNcW

Using OpenCL platform: NVIDIA CUDA
gpu#0: GeForce GTX 1070
gpu#1: GeForce GTX 960
zec-sa#0 loading binary kernels/cache/zec-sa-GeForce GTX 1070-64.bin
zec-sa#0: 0.0S/s        zec-sa#1 compiling kernels/zec-sa.cl...
zconn Connecting to zec.suprnova.cc:2142
zec-sa#1: 0.0S/s        total: 0.0S/s
zconn Connected!
zconn subscribed
zconn authorized worker Genoil.SilentArmy
zconn subscribed
zconn received new job #11
zec-sa#0clEnqueueReadBuffer(-5)
zec-sa#0 Mining thread quit
E:\Mining\genoil-zec-miner-0.4.2>pause`

**Comment by Genoil** [comment]
this miner is aimed at AMD for now. SilentArmy v4 will support Nvidia, so I gues we'll have to wait a bit.
