### ISSUE TITLE
conversion of data to type "bool" failed

### ISSUE THREAD

**Issue by cmos99** [Genoil/ZECMiner#45]
Hi 

issue below encountered. windows 8 x64 5 x RX480 cards

zec-sa#4 loading binary zconn Connected!kernels/cache/zec-sa-Ellesmere-64.bin

zconn subscribed
conversion of data to type "bool" failed
Retrying in 5 seconds...

**Comment by Genoil** [comment]
i think this is an incident due to high traffic on pool, not a real bug on my end.
