### ISSUE TITLE
why not start with the option -i?

### ISSUE THREAD

**Issue by igorkiev36** [Genoil/ZECMiner#46]
Hello!
why not start with the option -i?
Win 7 64  AMD R9 390X
Genoil's ZEC miner
releases/genoil-zec-miner-0.4.2.zip
genoil.exe -c zec.suprnova.cc:2142 -u adr -p x -P 0 -g 0 -i 13

**Comment by Genoil** [comment]
this is disabled from 0.4 onwards. will be back in next release.
