### ISSUE TITLE
0.4.2

### ISSUE THREAD

**Issue by ghost** [Genoil/ZECMiner#47]
0.4.2 still dont work GCN 1.0 (r9 270) when try compile binary it crash. zec_sa.cl. sometimes it compile binary into cache folder but when run, whole system freeze and need hard reboot.

other time it run but 0.0/s and really laggy windows. tried with cl-extragpumem 64 and it crashes after pool connect 100% of the time.

**Comment by mehtaman** [comment]
ditto - Windows freezes and needs a hard reboot sometimes, even with the latest verision.

**Comment by lukeinpanama** [comment]
Has anyone tried decreasing the intensity?

**Comment by ghost** [comment]
trying 0.5, seems to be working with amazing hashrate boost.
will edit if pool is recording it properly 

EDIT: 0.5 has solved this issue
