### ISSUE TITLE
job not found

### ISSUE THREAD

**Issue by BobDoe** [Genoil/ZECMiner#49]
zec-sa#0: 26.5S/s       total: 26.5S/s
zec-sa#0: 27.5S/s       total: 27.5S/s
zec-sa#0: 26.3S/s       total: 26.3S/s
zec-sa#0: 28.3S/s       total: 28.3S/s
zec-sa#0 submitting solution
zconn not accepted: job not found (21)
zec-sa#0: 21.7S/s       total: 21.7S/s
zec-sa#0: 25.7S/s       total: 25.7S/s
zec-sa#0: 24.9S/s       total: 24.9S/s
zec-sa#0: 23.1S/s       total: 23.1S/s
zec-sa#0 submitting solution
zconn not accepted: job not found (21)
zec-sa#0 submitting solution
zconn not accepted: job not found (21)
zec-sa#0: 24.3S/s       total: 24.3S/s
zec-sa#0: 26.3S/s       total: 26.3S/s
zec-sa#0: 20.2S/s       total: 20.2S/s
zec-sa#0: 25.3S/s       total: 25.3S/s
zec-sa#0 submitting solution
zconn not accepted: job not found (21)
zec-sa#0 submitting solution
zconn not accepted: job not found (21)
zec-sa#0 submitting solution
zconn not accepted: job not found (21)
zec-sa#0: 23.1S/s       total: 23.1S/s
zec-sa#0 submitting solution
zconn not accepted: job not found (21)
zec-sa#0: 25.9S/s       total: 25.9S/s

runs great with solutions being accepted until this happens         ( zec-sa#0 submitting solution
zconn not accepted: job not found (21)
 it never recovers until it is shut down and restarted

**Comment by BobDoe** [comment]
suspect varidiff with supernova somehow the miner and the pool get out of sync????

win 10/64  this is RX-480, 
However I have a rig with AMD 7950, R7-370, R9-380, R9-380X, R9-390 and it has same behavior ( job not found ) after pool adjusts Difficulty

**Comment by Genoil** [comment]
Fixed in 0.5

**Comment by BobDoe** [comment]
Thank You so much for all your HARD WORK :)
