### ISSUE TITLE
0.6 close without reason + high cpu usage at startup

### ISSUE THREAD

**Issue by coreytaylor211** [Genoil/ZECMiner#69]
Hi guys,
The program closes without a message in the logs also is nothing.
The cpu usage at startup is very high, is this normal?

**Comment by coreytaylor211** [comment]
Update 

program closes without reason - solved
(Another program that triggered the error.)

![20161102_153444](https://cloud.githubusercontent.com/assets/1409887/19933217/ec6486c8-a112-11e6-94c6-0ec973950878.jpg)

**Comment by privatenode** [comment]
high CPU usage could be resolve with -k zec zec, as many zec as your cpu threads got.
