### ISSUE TITLE
no fix for 0 sol/s a huge problem random hour happen

### ISSUE THREAD

**Issue by masoodarny** [Genoil/ZECMiner#87]
nothing to say i am sick of it...same problem again again and again but no fix...:(

**Comment by The-Lightbearer** [comment]
me too man, this miner really needs major work. But Claymores is coming out!

**Comment by masoodarny** [comment]
hey bro when

**Comment by dragun05** [comment]
me too man, randow 0sol/s. Waiting Claymores out!

**Comment by whitematrix62** [comment]
I have no idea why you guys need to be so rude. Please don't troll here and be thankful that Genoil is sharing his work. If you know any programming you can easily hack a script. Please get off your high horse.

**Comment by goodlivin** [comment]
@whitematrix62 Well said!

**Comment by Genoil** [comment]
I understand it is frustrating and I understand you're waiting for a solid Claymore release, too. But when you finally get your 100sol/s whatever steady Claymore miner and sell your hard earned ZEC at < 1 BTC - ZEC, remember the scruffy Genoil ZECMiner that got you double the profit with less than half the sol/s in the first week. That is the whole frikkin' point of rapid prototyping, geez.

**Comment by stevehang** [comment]
Couldn't agree any more , you done well Genoil, im happy with version 4.1!!

**Comment by jch9678** [comment]
@miningpoolhub changed something on his pool and I my disconnects have drastically reduced.  I may not have even had any overnight on some machines.  Give it a shot

https://zcash.miningpoolhub.com/

**Comment by masoodarny** [comment]
Sorry for that ....you are right bro...we all are thankfully to gen oil...

On Nov 4, 2016 9:30 PM, "jch9678" notifications@github.com wrote:

@miningpoolhub https://github.com/miningpoolhub changed something on his
pool and I my disconnects have drastically reduced. I may not have even had
any overnight on some machines. Give it a shot

https://zcash.miningpoolhub.com/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Genoil/ZECMiner/issues/87#issuecomment-258460460, or mute
the thread

**Comment by rodgermoore** [comment]
Hey @masoodarny and @The-Lightbearer did you use this batch script?

```
:loop
genoil.exe -f 2 -c eu1-zcash.flypool.org:3333 -u YourAddressHere.YourRigName -p z
timeout /t 1 /nobreak
goto :loop
```

This will restart genoil when you hit 0 sol/s.

**Comment by masoodarny** [comment]
thanks ....you are the only one that help me and not angry with me ...i just discuss the problem ...and you just looked what happened...my dear bro @whitematrix62  nothing to say bro and thanks bro @rodgermoore,,,and you @The-Lightbearer  i in the same page...and i respect and thakful to @Genoil ...May Allah bless us All...problem is solved
