### ISSUE TITLE
Write your hashrates please.

### ISSUE THREAD

**Issue by mokrejbandita1** [Genoil/ZECMiner#88]
Hello I am curious, what hashrates are you getting with your GPU cards. Please write vendor, clockings, software and average hashrate for single card to keep it simple.
For me its:
win7
Sapphire 280x, (1050/1500),catalyst 15.2, genoil 0.5 - 23sol/s
Asus 290x ref (1000/1250), catalyst 15.2, genoil 0.5 - 26-27sol/s

Thanks

**Comment by jtremblaytdst** [comment]
With genoil and my 390x i have 23-31S/s. With Zogminer i get 40 all the time :D

**Comment by Bitminereu** [comment]
With Nicehash Miner 0.4b - latest version.
2 x rx480 - 64/66 sol/s
6 x rx470 - 150/160 sol/s
1 gtx1070 + i7 3700k 6 Thread - 45/50 sol/s

**Comment by d57heinz** [comment]
for those of you running the 290x and 390x.. create a separate bat for that gpu only and run two instances of genoil. You get north of 40 - 45 sols/s .. i have tried -k zec zec to get what i think is the same result only for it to crash immidiately and it doesnt seem to improve hashrate.  so i just run two waiting for the first one to load completely and then the second one..

**Comment by eds17** [comment]
Genoil miner v6...  - catalyst 15.12...  I have 5 x sapphire Nanos all running under-volted...  and 1 x  i7 4770T getting 120 sol/s  and total systems out puts at the walls adds up to 395 watts.
Electricity is quit expensive in my location :)

**Comment by zcashdarkcoin** [comment]
Sapphire 280x, (1215/1750), Crimson 16.11.1, genoil 0.6 - around 31sol/s

**Comment by withthelemons** [comment]
Sapphire 280x, (1215/1750), Crimson 16.11.1, genoil 0.6 - around 32sol/s
Sapphire 470 4GB (1400/1875), Crimson 16.11.1, genoil 0.6 - around 34sol/s

**Comment by masoodarny** [comment]
win 10 15.12 gigabyte r9 390 37-47 sol/s  1155/1500
core i 5 4th generation 4590 3.3 ghz  11 sol/s

**Comment by eds17** [comment]
I've also tested these components and here are the results:
i7 4770T sock 1150 - 20 - 22 sol/s
i7 4770TE  sock 1150- 20 - 22 sol/s
i5 3470 sock 1155  - 16 - 20 sol/s
i3 4130T sock 1150 - 10 -11 sols/
Pentium g3240T sock 1150  - 4 sol/s
Laptop Lenovo T420s with i5 2540m  -   8 - 9 sol/s
Laptop Asus G750JM with i7  -  16 - 20 sol/s
Xeon E5-2630L sock 2011  -  16 sol/s

**Comment by tuzak500** [comment]
xfx gtr rx 480 30-34 sol stock

**Comment by masoodarny** [comment]
extreme overclock r9 390 58-59 + sol/s

2016-11-06 8:27 GMT+06:00 tuzak500 notifications@github.com:

**Comment by kwaaak** [comment]
4x R9 270 running @ 1150 Core + 1500 Mem:
Total 92.1 sol/s [dev0 22.6, dev1 25.0, dev2 20.8, dev3 24.5] 5 shares

**Comment by jtremblaytdst** [comment]
7x R9 390x = 320S/s

**Comment by ghost** [comment]
5x R9 390x and 2x R9 390 = 650-670S/s with silentarmy miner on ubuntu 14.4 with crimson

**Comment by Genoil** [comment]
I love u guys for being informatieve to eachother but this is not a forum. Sorry to close this.

**Comment by masoodarny** [comment]
r9 390 145 hash/s 15.12 overclocked
cpu 12 hash/s core i5 4590

2016-11-15 12:36 GMT+06:00 Genoil notifications@github.com:
