### ISSUE TITLE
R9 280X AMD's do not work on Win 7 or Win 8

### ISSUE THREAD

**Issue by tuppydog** [Genoil/ZECMiner#9]

**Comment by gennadiv** [comment]
у меня то-же не работает r9 380 3 карты

**Comment by tuppydog** [comment]
Плохой парень нуждается в режим сна

**Comment by molitar** [comment]
I have the same exact problem!

**Comment by tuppydog** [comment]
Got the R9 280x to work on the new genoil-zec-miner-0.4.2! Delete the bin, run it a few times, all of a sudden it works perfectly, running 4 GPUs, with a dual processor.
