### ISSUE TITLE
ErroR Genoil.exe (0xc00007b)

### ISSUE THREAD

**Issue by iroshimasan** [Genoil/ZECMiner#90]
As you can see, I'm having problems with my genoil, it does not open before it was due to lack of .dll. now I do not know WHAT more can be

i am usin W10, 64bit

![unknown](https://cloud.githubusercontent.com/assets/13550363/20029864/2059e2b0-a33f-11e6-8c47-ac08de5c6c19.png)
![unknown](https://cdn.discordapp.com/attachments/240297596512370688/244411443989053440/unknown.png)

**Comment by iroshimasan** [comment]
Solved

**Comment by WakhraDJ** [comment]
How was the issue resolved?
